[pytest]
asyncio_mode = auto
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning:websockets.*:
    ignore::DeprecationWarning:starlette.*:
    ignore::DeprecationWarning:pytest_asyncio.*:
    ignore::DeprecationWarning:fastapi.*: