# This is an example docker compose for running on network mode host (needed to test against mock)

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    restart: unless-stopped

  nmos_exporter:
    image: nmos-exporter
    container_name: nmos_exporter
    network_mode: "host"
    restart: unless-stopped

volumes:
  prometheus_data:
