{
 "title": "nmos_exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(nmos_overall_status,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nmos_overall_status{instance=\"nmos_node_01:8080\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  },
  {
   "title": "Enabled State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nmos_enabled{instance=\"nmos_node_01:8080\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connection Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "nmos_connection_status{instance=\"$node\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  },
  {
   "title": "Connection Status Transitions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nmos_connection_status_transition_counter{instance=\"$node\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  },
  {
   "title": "Link Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "nmos_link_status{instance=\"$node\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  },
  {
   "title": "Link Status Transitions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nmos_link_status_transition_counter{instance=\"$node\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  },
  { "title": "Synchronisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Synchronisation Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "nmos_external_synchronization_status{instance=\"$node\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  },
  {
   "title": "Synchronisation Source ID ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "nmos_synchronization_source_id{instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stream Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Essence Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "nmos_essence_status{instance=\"$node\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  },
  {
   "title": "Essence Status Transitions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nmos_essence_status_transition_counter{instance=\"$node\"}",
     "legendFormat": "{{monitor_label}}"
    }
   ]
  }
 ]
}